### ISSUE TITLE
Release: HAL 0.3.0, RAL 0.3.0

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-rs#59]
We've accumulated a decent set of features and fixes in the HAL ([CHANGELOG](https://github.com/imxrt-rs/imxrt-rs/blob/d02bcc339c626ff21ae2a5727bbc4515d5963259/imxrt-hal/CHANGELOG.md#unreleased)). There's one more HAL feature pending in #58. And, once #57 is merged, we will have fixed the RAL's documentation. Given the updates, I'd like to cut a release of both crates.

- `imxrt_hal` minor bump to `0.3.0`
- `imxrt_ral` ~~patch~~ feature bump to ~~`0.2.2`~~ 0.3.0.

Release will gate on #57 and #58. I'm shooting for 2020/06/17 as the earliest release date.

Let me know if we'd like more time to prepare!

**Comment by mciantyre** [comment]
I might also include #60, which would increment the RAL to `0.3.0`.

**Comment by bfrog** [comment]
This sounds good to me, release when ready
