### ISSUE TITLE
Port HAL to the RAL

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-rs#8]
The issue tracks how much of the HAL is migrated from the PAC-based implementation to the RAL-based implementation.

- [x] CCM
- [x] GPIO
- [x] I2C
- [x] IOMUXC
- [x] PIT
- [x] PWM
- [x] SPI
- [x] UART

My focus is on keeping parity with the existing features; for example, I don't intend on generalizing the HAL for other iMXRTs right now. Once I can build the HAL, I can show equivalence by [using the examples in the `teensy4-examples` crate](https://github.com/mciantyre/teensy4-rs/tree/master/teensy4-examples/src).

**Comment by mciantyre** [comment]
IOMUXC is WIP on `hal_iomux`

**Comment by mciantyre** [comment]
Ported IOMUXC in #10

**Comment by bfrog** [comment]
Initial iomuxc work done and merged, on to the next thing. I plan on trying to deal with GPIO stuff this week so I can get the typical blinky led example working on the 1060evk. I also picked up a teensy so I can start testing the teensy examples you've made.

**Comment by mciantyre** [comment]
Awesome thanks. I can start the I2C peripheral unless there’s something else you’d like to see.

**Comment by bfrog** [comment]
I2C sounds great, will be super happy when we get a uart going as well :+1:

**Comment by mciantyre** [comment]
I2C port proposed in #11.

**Comment by bfrog** [comment]
GPIO in progress, but noticed I think a case where our unsafe usage really is in fact unsafe, see #21. Something I think we'll need to consider what each option means

**Comment by bfrog** [comment]
GPIO wrapped up, though future improvements to iomux+gpio are definitely possible to better take advantage of rusts ownership and mutability rules to avoid the critical section

**Comment by bfrog** [comment]
@mciantyre did you want to try to tackle pwm or should I? I can hammer it out here I think pretty quick, don't want to step on your toes if you are already on it

**Comment by mciantyre** [comment]
I haven't started on PWM yet, but I'm happy to pick it up. I might not get to it until this weekend.

PWM might be the least straightforward to port. When we implemented the driver on the `svd2rust` output, we were taking advantage of SVD `<cluster>`s being represented as a struct. But, the RAL approach doesn't represent SVD clusters (#2); it simply duplicates the registers. This might require us to change a good bit of the implementation; it might be more macro-heavy. There might be some parts of the RAL API that I'm not considering, so I'm going to study up on that.

If it makes it easier to port the PWM driver, I might consider implementing [`embedded_hal::Pwm`](https://docs.rs/embedded-hal/0.2.3/embedded_hal/trait.Pwm.html) instead of [`embedded_hal::PwmPin`](https://docs.rs/embedded-hal/0.2.3/embedded_hal/trait.PwmPin.html).

**Comment by bfrog** [comment]
I'll let you tackle PWM then, it sounds like you have some good ideas on what needs to happen.

I'm going to start looking at making sure what we have works on my 1060 evk and fixing bugs as I find them as time permits.

 I can help with the teensy testing when that time comes.

Once things are mostly working on the 1060evk and teensy 4 I'm happy to say this is 0.1 worthy and iterate from there if you are. I certainly have some ideas on where to go next we can maybe chat about in issues or on a video meetup/voice meet if that's something you are interested in at all.

**Comment by bfrog** [comment]
I think we can safely close this issue, unless you know of anything left to port @mciantyre

**Comment by mciantyre** [comment]
All good!
